GET http://localhost:8080/contacts/
###
GET http://localhost:8080/contacts/678afe49dbc96b80ae1c91f9
###
GET https://cse341-hx1h.onrender.com/contacts
###
GET https://cse341-hx1h.onrender.com/contacts/678afe49dbc96b80ae1c91f9
